openLibrary:
  apiBaseUrl: "https://openlibrary.org"

s3:
  accessKey: "accessKey"
  secretKey: "secretKey"
  endpoint: "http://localhost:9090"
  bucket: "bucket"

server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive-training
      authenticationDatabase: admin
      username: root
      password: root
